spring:
  #   base de datos posta
  datasource:
    url: jdbc:postgresql://localhost:5433/booklibre
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000
      initialization-fail-timeout: 1

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # base documental
  data:
    mongodb:
      uri: mongodb://admin:admin@127.0.0.1:27019/book_libre?authSource=admin
      auto-index-creation: true

# Para activar el Trace
logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
    org.postgresql: DEBUG
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: DEBUG

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 900000
  refresh-token-expiration: 1800000